platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    if is_ci
      create_keychain(
        name: ENV['MATCH_KEYCHAIN_NAME'],
        password: ENV["MATCH_KEYCHAIN_PASSWORD"],
        default_keychain: true,
        unlock: true,
        timeout: 3600,
        lock_when_sleeps: false
      )
    end
    match(
      type: "appstore",
      readonly: is_ci,
      keychain_name: ENV['MATCH_KEYCHAIN_NAME'],
      keychain_password: ENV["MATCH_KEYCHAIN_PASSWORD"],
    )

    xcversion(version: "12.3")

    increment_build_number(
      xcodeproj:"urbanfitsample.xcodeproj"
    )

    increment_version_number(
      xcodeproj:"./urbanfitsample.xcodeproj"
    )

    commit_version_bump(
      message:"chore: Version Bump",
      xcodeproj:"./urbanfitsample.xcodeproj",
      force: true
    )

    push_to_git_remote(
      remote: "origin",
      local_branch: "develop",
      remote_branch: "develop",
      force: true,
      force_with_lease: true,
      tags: false,
      no_verify: true,
      set_upstream: true
    )

    build_app(
      workspace: "urbanfitsample.xcworkspace",
      scheme: "urbanfitsample",
      export_method: "app-store"
    )

    upload_to_testflight

  end
end