name: Distribute beta to firebase & testflight
on:
  push:
    branches:
      - 'cp/fix-fastlane'

jobs:
  distribute-android:
    name: Distribute android apk to firebase

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x'

      - name: Install packages
        run: |
          yarn install
          yarn react-native link

      - name: Install Fastlane
        run: cd ./android && gem install fastlane

      - name: Distribute to firebase
        run: cd ./android && fastlane android distribution
        env:
          FIREBASE_APP_ID_ANDROID: ${{ secrets.FIREBASE_APP_ID_ANDROID}}
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}